language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer --dev install

script:
  - php ./vendor/bin/phpunit --coverage-text --coverage-clover ./../build/logs/clover.xml -c ./tests/.
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_script:
  - php vendor/bin/coveralls -v
